DROP TABLE IF EXISTS Address;

CREATE TABLE Address (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    street TEXT NOT NULL,
    name TEXT NOT NULL,
    state TEXT NOT NULL,
    city TEXT NOT NULL
);