DROP TABLE IF EXISTS wheredata;

CREATE TABLE wheredata (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    street TEXT NOT NULL,
    name TEXT NOT NULL,
    state TEXT NOT NULL,
    city TEXT NOT NULL
);