DROP TABLE IF EXISTS addresses CASCADE;
DROP TABLE IF EXISTS access;
DROP TABLE IF EXISTS directions;

CREATE TABLE addresses (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    street TEXT NOT NULL,
    name TEXT NOT NULL,
    state TEXT NOT NULL,
    city TEXT NOT NULL
);

CREATE TABLE access (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    accessible BOOLEAN NOT NULL
);

CREATE TABLE directions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    direction TEXT NOT NULL,
    address_name TEXT NOT NULL
);
